let content = [
  {
    name: "Android 应用程序",
    id: "android_applications",
    items: [
      {
        name: "Aide Lua",
        id: "aidelua",
        summary: "为更方便的移动开发",
        image: "/images/graphs/aidelua.webp",
        src: "https://aidelua.github.io/",
        icon: "home-outline",
        "url-type": "主页",
      },
      {
        name: "Edde Lua",
        id: "eddelua",
        summary: "为更好看的用户界面",
        image: "/images/graphs/aidelua.webp",
        src: "/aidelua/",
      },
      {
        name: "AndroLuaX",
        id: "androluax",
        summary: "添加了 AndroidX 的 AndroLua+",
        image: "/images/graphs/androluax.webp",
        src: "https://gitlab.com/Jesse205/androluax",
        icon: "source-branch",
        "url-type": "GitLab 仓库",
      },
      {
        name: "哈兔Box",
        id: "hellotool",
        summary: "简洁蓝白风工具箱",
        image: "/images/graphs/aidelua.webp",
        src: "/hellotool/",
        icon: "home-outline",
        "url-type": "主页",
      },
      {
        name: "桌面时钟 Lite",
        id: "deskclock_lite",
        summary: "占用低、兼容性强的时钟",
        image: "/images/graphs/deskclock_lite.svg",
        'dark-image': "/images/graphs/deskclock_lite_dark.svg",
        src: "https://gitlab.com/Jesse205/Desk-Clock-Lite",
        icon: "source-branch",
        "url-type": "GitLab 仓库",
      },
      {
        name: "拖放中转站",
        id: "drag_and_drop_transfer_station",
        summary: "中转任何拖放文本与文件",
        image: "/images/graphs/drag_and_drop_transfer_station.png",
        src: "https://gitee.com/Jesse205/DragAndDropTransferStationLite",
        icon: "source-branch",
        "url-type": "GitHub 仓库",
      },
    ],
  },
  {
    name: "Windows 软件",
    id: "windows_softwares",
    items: [
      {
        name: "畅玩6X工具箱",
        id: "honor6xtools",
        summary: "不止为畅玩6X开发",
        image: "/images/graphs/honor6xtools.webp",
        src: "https://gitee.com/Jesse205/Honor6XTools",
        icon: "source-branch",
        "url-type": "Gitee 仓库",
      },
      {
        name: "F-OH Tauri",
        id: "foh_tauri",
        summary: "基于 F-OH PWA 的跨平台客户端",
        image: "/images/graphs/foh_pwa.svg",
        "dark-image": "/images/graphs/foh_pwa_dark.svg",
        src: "https://gitee.com/Jesse205/F-OH-PWA",
        icon: "source-branch",
        "url-type": "Gitee 仓库",
      },
    ],
  },
  {
    name: "PWA 应用",
    id: "pwa_applications",
    items: [
      {
        name: "百度一下 Lite",
        id: "baiduhome_lite",
        summary: "特别简洁的浏览器主页",
        image: "/images/graphs/baidu_lite.webp",
        src: "/baiduhomelite/",
        icon: "open-in-app",
        "url-type": "应用",
      },
      {
        name: "桌面时钟 Lite",
        id: "deskclock_lite",
        summary: "打开就能用的时钟",
        image: "/images/graphs/deskclock_lite.svg",
        'dark-image': "/images/graphs/deskclock_lite_dark.svg",
        src: "/deskclocklite/",
        icon: "open-in-app",
        "url-type": "应用",
      },
      {
        name: "F-OH PWA",
        id: "foh_pwa",
        summary: "跨平台的第三方在线 F-OH 客户端",
        image: "/images/graphs/foh_pwa.svg",
        "dark-image": "/images/graphs/foh_pwa_dark.svg",
        src: "https://gitee.com/Jesse205/F-OH-PWA",
        icon: "source-branch",
        "url-type": "Gitee 仓库",
      },
    ],
  },
  {
    name: "各种文档",
    id: "documents",
    items: [
      {
        name: "AndroLua+ 文档",
        id: "androlua",
        summary: "经过精心整理后的文档",
        image: "/images/graphs/androlua_document.webp",
        src: "https://aidelua.github.io/AideLua/androluapro/",
        icon: "file-document-outline",
        "url-type": "文档",
      },
      {
        name: "Magisk 中文文档",
        id: "magisk",
        summary: "精心机翻，仅供参考",
        image: "/images/graphs/magisk_chinese_document.webp",
        src: "https://jesse205.github.io/MagiskChineseDocument/",
        dark: false,
        icon: "file-document-outline",
        "url-type": "文档",
      },
      {
        name: "刷机指南",
        id: "flash_android_devices_guidlines",
        summary: "万能的刷机指南",
        image: "/images/graphs/flash_android_devices_guidlines.webp",
        src: "https://jesse205.github.io/FlashAndroidDevicesGuidelines/",
        dark: false,
        icon: "file-document-outline",
        "url-type": "文档",
      },
    ],
  },
]
